default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: capstone_project_development

test:
  <<: *default
  database: capstone_project_test

production:
  <<: *default
  database: capstone_project_production
  username: capstone_project
  password: <%= ENV['CAPSTONE_PROJECT_DATABASE_PASSWORD'] %>
